name: "CartPole Environment"
type: "CartPole-v1"
version: "1.0.0"

# Environment parameters
parameters:
  # Common parameters
  max_steps: 500
  reward_scale: 1.0
  
  # Environment-specific parameters
  env_specific:
    gravity: 9.8
    masscart: 1.0
    masspole: 0.1
    length: 0.5
    force_mag: 10.0
    
# Observation space configuration
observation_space:
  type: "continuous"
  shape: [4]
  low: [-4.8, -Infinity, -0.418, -Infinity]
  high: [4.8, Infinity, 0.418, Infinity]
  
# Action space configuration
action_space:
  type: "discrete"
  n: 2
  
# Rendering configuration
rendering:
  enabled: true
  mode: "human"
  fps: 30
